import "./globals.css";
import { Metadata } from "next";
import { ThemeProvider } from "@/prisma/providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Mãi bên nhau bạn nhó",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <ThemeProvider>{children}</ThemeProvider>;
}
